require.config({
    baseUrl:"/",
    paths:{
        "jquery":["https://code.jquery.com/jquery-1.12.4.min","lib/jquery/jquery-1.12.4.min"],
        "cookie":"lib/jquery_plugins/jquery.cookie",
        "template":"lib/arttemplate/template",
        "loadHeaderFooter":"js/loadHeaderFooter"
    }
});